---
title: "About the analysis"
author: "Gabriel Lages"
date: "13/09/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This website contains a independent study about "Brazilian Artificial Accounts" case.

Currently in Brazil one of the most widely discussed topic in political is the "fiscal pedaling" practiced by the federal government during the year of 2014. According to [Valor Econômico](http://www.valor.com.br/node/4100334) (a famous brazilian newspaper) "fiscal pedaling" is the popular name of a trick used by the brazilian government to artificially improove public account.

## Data Source

This study contains Data from 2 different government sources.

1. [BACEN](http://www.bcb.gov.br/en/#!/home) (Central Bank of Brazil)
2. [TCU](http://portal.tcu.gov.br/english/home.htm) (The Federal Court of Accounts of Brazil)

*All data were collected in september 2016.

## More Information

This study is part of Developing Data Products Course from Coursera.
This is not a political study, the only objective is to test different kind of online data visualization tools.

If you still have any observation about the study please send an email to gabrielclages@gmail.com.
